### ISSUE TITLE
srli causes register value to be interpreted as unsigned by ecall

### ISSUE THREAD

**Issue by Naftoreiclag** [kvakil/venus#14]
The print function of `ecall` in does not print consistent results if a right-shift arithmetic of zero bits is applied on `a1` before calling `ecall`.

```riscv
# Expected behavior:
lui a1, 0xDAF70
addi a0, x0, 1
ecall # Prints -621346816
```
```riscv
# Anomalous behavior:
lui a1, 0xDAF70
srli a1, a1, 0 # Do nothing (?)
addi a0, x0, 1
ecall # Prints 3673620480
```
Note that `3673620480` exceeds the maximum value of a 32-bit signed integer, `2147483647`. (Which, as far as I know, is how RISC-V interprets the contents of the registers by default.) Also note that `-621346816` and `3673620480` have exactly the same bit pattern as a 32-bit signed and unsigned word, respectively.

Venus reports the following register values in both cases:
```
a0: 0x00000001
a1: 0xdaf70000
```

Tested on Firefox 56.0.1 (64-bit) Windows 7 and lubuntu 17.04, and Chrome 61.0.3163.100 (Official Build) (64-bit), Opera 48.0.2685.39 (PGO) all on Windows 7.

**Comment by kvakil** [comment]
Thanks for reporting this!

This actually isn't my fault (_surprisingly_), it's a problem with the KotlinJS compiler. I've opened a bug upstream and added a patch to fix this in the meantime.
