### ISSUE TITLE
http://www.kvakil.me/venus/ misses bgtz support

### ISSUE THREAD

**Issue by jlusiardi** [kvakil/venus#16]
Hi,

I am not sure if this problem is in the most current version, but on http://www.kvakil.me/venus/ I get an error on 
```
l1: bgtz  t2 l1
```
It tells me, "instruction with name bgt not found". 
Can you fix this please?

Regards
Joachim

**Comment by kvakil** [comment]
Should be fixed now, cheers for the report.

**Comment by jlusiardi** [comment]
Confirmed working. Thx a lot!
