### ISSUE TITLE
sub instruction

### ISSUE THREAD

**Issue by schoeberl** [kvakil/venus#6]
maybe I missed soemthing substantual, but following code gives an issue:

addi x1, x0, 123
addi t0, x0, 456
sub x3, x1, t0

When tryning to simulate I get an error on sub not a legal insatruction.

cheers,
Martin

**Comment by kvakil** [comment]
Sorry about that! I'm in the middle of some internal refactoring. `sub` should work now, although RV32M is still missing.

**Comment by schoeberl** [comment]
Ok, cool! Works again. Thanks!

Any plans to have stable releases so I can use venus for taching in fall?

**Comment by kvakil** [comment]
Yes, I'll have a stable version out by
