### ISSUE TITLE
Memory displays only zeros

### ISSUE THREAD

**Issue by schoeberl** [kvakil/venus#8]

**Comment by kvakil** [comment]
That's strange; it seems to work fine on my end:

![memdisplay](https://user-images.githubusercontent.com/22647613/29332980-ddf9d400-81b6-11e7-8a45-5b00a1f8debc.png)

Can you send a picture of what you're seeing?

**Comment by schoeberl** [comment]
Update: it is a resolution issue. On the iPad I see only zeros. On my Laptop (Mac) I see almost only zeros, just with a hint of an x. Please make sure that also lower resolution devices work, and not only your big screen ;-)

Is editing the memory really such an important option? Venus gets more complex and looses its simplicity. E.g., I can now edit the instruction, but I don't see this change in the instruction view. Now the code view is inconsistent from the memory view.

**Comment by schoeberl** [comment]
![img_0712](https://user-images.githubusercontent.com/650648/29333824-906ad9ce-8205-11e7-85a0-7ab0b6d8fa3b.PNG)

**Comment by schoeberl** [comment]
Also the vertical resolution is a bit too high, but one can move.

**Comment by kvakil** [comment]
These are some good points. For now I've reverted back to the old memory display.

Keeping venus simplistic and easy-to-use is an important goal to me and I will try to balance that against adding new features.

**Comment by schoeberl** [comment]
Ok, cool. Can read it again.
![img_0713](https://user-images.githubusercontent.com/650648/29336866-99e4de64-820f-11e7-9a09-4d80e3577463.PNG)
